# Generated by Django 4.2 on 2023-05-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
