# Generated by Django 4.2 on 2023-05-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
