# Generated by Django 4.2 on 2023-05-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_amount_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
