# Generated by Django 4.2 on 2023-05-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='assertment',
            new_name='rating',
        ),
    ]
