# Generated by Django 4.2 on 2023-05-08 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
