# Generated by Django 4.2 on 2023-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=40)),
                ("stock", models.IntegerField()),
                (
                    "cart",
                    models.ManyToManyField(
                        related_name="products_in_cart",
                        through="products.CartProducts",
                        to="carts.cart",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
