# Generated by Django 4.2 on 2023-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_wishlistproducts_product_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.IntegerField(default=0),
        ),
    ]
